# Generated by Django 4.2.23 on 2025-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClosingPriceLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stockid", models.CharField(max_length=10)),
                ("date", models.DateTimeField()),
                ("closing_price", models.FloatField()),
                ("updown_rate", models.FloatField()),
            ],
            options={"db_table": "closing_price_log",},
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "industry_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("industry_name", models.CharField(max_length=10)),
            ],
            options={"db_table": "industry",},
        ),
        migrations.CreateModel(
            name="KisToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token_value", models.TextField()),
            ],
            options={"db_table": "kis_token",},
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("industry_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=40)),
                ("volume_power", models.FloatField(null=True)),
                ("current_price", models.FloatField(null=True)),
                ("type", models.CharField(max_length=10, null=True)),
                ("eq", models.IntegerField(null=True)),
                ("country", models.CharField(max_length=2, null=True)),
                ("updown_rate", models.FloatField(null=True)),
            ],
            options={"db_table": "stock",},
        ),
    ]
