# Generated by Django 4.2.23 on 2025-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyStock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stockid", models.CharField(max_length=10)),
                ("userid", models.IntegerField()),
                ("cnt", models.IntegerField(null=True)),
                ("average_cnt", models.IntegerField(null=True)),
                ("date", models.DateTimeField(null=True)),
            ],
            options={"db_table": "mystock",},
        ),
    ]
