# Generated by Django 4.2.23 on 2025-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                (
                    "stock_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("stockid", models.CharField(max_length=10)),
                ("categoryid", models.IntegerField()),
            ],
            options={"db_table": "stock_category",},
        ),
        migrations.AlterModelTable(name="category", table="category",),
    ]
